meta_name: "Kenkou Match"
meta_title: "Kenkou Match - Match your health"
meta_description: "Kenkou Match helps you find local medical specialists.Our unique \"Kenkou Card\" offers an ai-assisted study card to help you better communicate your needs to medical profressionals."
meta_image: "kenkou-banner.svg"
twitter_account: "@your_twitter_account"
